sudo: required

services:
  - docker

language: php

php:
  - 5.6
  - 7.0
  - 7.1

env:
  - DOCKER_COMPOSE_VERSION=1.14.0
  - ISOLATED=true

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - docker --version
  - docker-compose --version

before_script:
  - phpenv config-rm xdebug.ini
  - npm install
  - composer install
  - sudo chmod -R 777 vendor
  - grunt default

matrix:
  include:
  - php: "7.1"
    env:
      - PRESTAHOP=prestashop17
      - ISOLATED=true
  - php: "7.0"
    env:
      - PRESTAHOP=prestashop16
      - ISOLATED=true
  - php: "5.6"
    env:
      - PRESTAHOP=prestashop15
      - ISOLATED=true
script:
  - sudo chmod -R 777 vendor
  - grunt shell:$PRESTASHOP

