sudo: required

language: php

services:
  - docker

language: php

php:
    - 5.6

before_script:
  - 'npm install'
  - 'composer install'
  - 'sudo chmod -R 777 vendor'

script:
  - 'grunt default'
  - 'sudo chmod -R 777 vendor'
  - 'grunt shell:runTestPrestashop16'
  - 'sudo chmod -R 777 vendor'
  - 'grunt shell:runTestPrestashop17'

