version: 2.1
commands:
  host_and_docker_compose:
    description: "Add Docker Host && DockerCompose install"
    steps:
      - run:
          name: Add Docker Host && DockerCompose install
          command: |
            export DOCKERHOST=$(ifconfig | grep -E "([0-9]{1,3}\.){3}[0-9]{1,3}" | grep -v 127.0.0.1 | awk '{ print $2 }' | cut -f2 -d: | head -n1)
            echo 127.0.0.1 prestashop15-test.docker | sudo tee -a /etc/hosts
            echo 127.0.0.1 prestashop16-test.docker | sudo tee -a /etc/hosts
            echo 127.0.0.1 prestashop17-test.docker | sudo tee -a /etc/hosts
            sudo curl -L https://github.com/docker/compose/releases/download/1.23.2/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
  install_dependencies:
    description: "Install php7.2 && Composer Install"
    steps:
      - run:
          name: Install php7.2 && Composer Install
          command: |
            sudo apt install -y software-properties-common
            sudo add-apt-repository -y ppa:ondrej/php
            sudo apt-get update
            sudo apt-get install -y php7.2-fpm php7.2-gd php7.2-curl php7.2-mysql php7.2-dev php7.2-cli php7.2-common php7.2-mbstring php7.2-intl php7.2-zip php7.2-bcmath php7.2-dom npm
            curl -s https://getcomposer.org/installer | php
            sudo mv composer.phar /usr/local/bin/composer
            composer install
  npm_grunt:
    description: "Npm Install && nvm-node && Grunt"
    steps:
      - run:
          name: Npm Install && nvm-node && Grunt
          command: |
            npm install
            curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh | bash
            export NVM_DIR="/opt/circleci/.nvm" && \. "$NVM_DIR/nvm.sh" && \. "$NVM_DIR/bash_completion"
            nvm install node
            node_modules/.bin/grunt
  run_tests:
    description: "Run Tests"
    steps:
      - run:
          name: Run Tests
          command: |
            export DOCKERHOST=$(ifconfig | grep -E "([0-9]{1,3}\.){3}[0-9]{1,3}" | grep -v 127.0.0.1 | awk '{ print $2 }' | cut -f2 -d: | head -n1)
            export NVM_DIR="/opt/circleci/.nvm" && \. "$NVM_DIR/nvm.sh" && \. "$NVM_DIR/bash_completion"
            nvm install node
            node_modules/.bin/grunt $PS_VERSION
jobs:
  runTestPrestashop17:
    environment:
      PS_VERSION: shell:runTestPrestashop17
    machine:
      image: ubuntu-1604:201903-01
    working_directory: ~/repo
    steps:
      - checkout
      - host_and_docker_compose
      - install_dependencies
      - npm_grunt
      - run_tests
  runTestPrestashop16:
    environment:
      PS_VERSION: shell:runTestPrestashop16
    machine:
      image: ubuntu-1604:201903-01
    working_directory: ~/repo
    steps:
      - checkout
      - host_and_docker_compose
      - install_dependencies
      - npm_grunt
      - run_tests
  pushRelease:
    docker:
      - image: circleci/php:7.1-node-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: NPM Install
          command: npm install
      - run:
          name: Package Generation
          command: |
            ./node_modules/.bin/grunt
            mv clearpay.zip clearpay-prestashop-$CIRCLE_TAG.zip
            ls *.zip
      - run:
          name: Install GitHub CLI
          command: |
            curl -LO https://github.com/aktau/github-release/releases/download/v0.7.2/linux-amd64-github-release.tar.bz2
            tar xfv linux-amd64-github-release.tar.bz2
            rm linux-amd64-github-release.tar.bz2
            sudo mv bin/linux/amd64/github-release /usr/local/bin/github-releaseÂº
            sudo chmod +x /usr/local/bin/github-release
      - run:
          name: Push ZIP to GitHub
          command: |
            github-release upload \
                --user pagantis \
                --repo prestashop \
                --tag $CIRCLE_TAG \
                --name pagantis-$CIRCLE_TAG.zip \
                --file pagantis-$CIRCLE_TAG.zip
workflows:
  version: 2
  build:
    jobs:
      - runTestPrestashop16:
          filters:
            branches:
              only: /.*/
      - runTestPrestashop17:
          filters:
            branches:
              only: /.*/
  release:
    jobs:
      - pushRelease:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/