version: 2.1
commands:
  host_and_docker_compose:
    description: "Add Docker Host && DockerCompose install"
    steps:
      - run:
          name: Add Docker Host && DockerCompose install
          command: |
            export DOCKERHOST=$(ifconfig | grep -E "([0-9]{1,3}\.){3}[0-9]{1,3}" | grep -v 127.0.0.1 | awk '{ print $2 }' | cut -f2 -d: | head -n1)
            echo 127.0.0.1 prestashop15-test.docker | sudo tee -a /etc/hosts
            echo 127.0.0.1 prestashop16-test.docker | sudo tee -a /etc/hosts
            echo 127.0.0.1 prestashop17-test.docker | sudo tee -a /etc/hosts
            sudo curl -L https://github.com/docker/compose/releases/download/1.23.2/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
  install_dependencies:
    description: "Install php7.2 && Composer Install"
    steps:
      - run:
          name: Install php7.2 && Composer Install
          command: |
            sudo apt install -y python-software-properties
            sudo add-apt-repository -y ppa:ondrej/php
            find /etc/apt/sources.list.d -type f -name '*.list' -exec sudo apt-get update -o Dir::Etc::sourcelist="{}" ';'
            sudo apt install -y php7.2-fpm php7.2-gd php7.2-curl php7.2-mysql php7.2-dev php7.2-cli php7.2-common php7.2-mbstring php7.2-intl php7.2-zip php7.2-bcmath php7.2-dom node
            curl -s https://getcomposer.org/installer | php
            sudo mv composer.phar /usr/local/bin/composer
            composer install
  npm_grunt:
    description: "Npm Install && Grunt"
    steps:
      - run:
          name: Npm Install && Grunt
          command: |
            npm install
            node_modules/.bin/grunt
  run_tests:
    description: "Run Tests"
    steps:
      - run:
          name: Run Tests
          command: |
            export DOCKERHOST=$(ifconfig | grep -E "([0-9]{1,3}\.){3}[0-9]{1,3}" | grep -v 127.0.0.1 | awk '{ print $2 }' | cut -f2 -d: | head -n1)
            grunt $PS_VERSION
jobs:
  runTestPrestashop17:
    environment:
      PS_VERSION: shell:runTestPrestashop17
    machine: true
    working_directory: ~/repo
    steps:
      - checkout
      - host_and_docker_compose
      - install_dependencies
      - npm_grunt
      - run_tests
  runTestPrestashop16:
    environment:
      PS_VERSION: shell:runTestPrestashop16
    machine: true
    working_directory: ~/repo
    steps:
      - checkout
      - host_and_docker_compose
      - install_dependencies
      - npm_grunt
      - run_tests
  runTestPrestashop15:
    environment:
      PS_VERSION: shell:runTestPrestashop15
    machine: true
    working_directory: ~/repo
    steps:
      - checkout
      - host_and_docker_compose
      - install_dependencies
      - npm_grunt
      - run_tests
workflows:
  version: 2
  build:
    jobs:
      - runTestPrestashop17
      - runTestPrestashop16
      - runTestPrestashop15
